AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sequence-alignment-api

  Sample SAM Template for sequence-alignment-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Resources:
  SequenceAlignmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri:
        !Join [
          ".",
          [
            !Ref AWS::AccountId,
            "dkr.ecr",
            !Ref AWS::Region,
            "amazonaws.com/",
            !Ref SequenceAlignmentRepo,
          ],
        ]
      Events:
        SequenceAlignment:
          Type: Api
          Properties:
            Path: /align
            Method: post
            Cors:
              AllowMethods: "'POST'"
              AllowOrigin: "'*'"
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./sequence-alignment
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SequenceAlignmentApi:
    Description: "API Gateway endpoint URL for Prod stage for SequenceAlignmentFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/align/"
  SequenceAlignmentFunction:
    Description: "SequenceAlignment Function ARN"
    Value: !GetAtt SequenceAlignmentFunction.Arn
  SequenceAlignmentFunctionIamRole:
    Description: "Implicit IAM Role created for SequenceAlignmentFunction"
    Value: !GetAtt SequenceAlignmentFunctionRole.Arn
